# Generated by AI 😔

def ascii_flipper(art: str) -> str:
    mirror_map = {
        '(': ')', ')': '(',
        '[': ']', ']': '[',
        '{': '}', '}': '{',
        '<': '>', '>': '<',
        '/': '\\', '\\': '/',
    }
    
    lines = art.splitlines()
    if not lines:
        return ""

    max_len = max(len(line) for line in lines)
    flipped_lines = []
    
    for line in lines:
        padded_line = line.ljust(max_len)
        # Using a list comprehension and join is faster and more "Pythonic"
        # It also avoids the += type-checking headache entirely
        flipped_chars = [mirror_map.get(c, c) for c in reversed(padded_line)]
        flipped_lines.append("".join(flipped_chars))
        
    return "\n".join(flipped_lines)